# Generated by Django 2.2.6 on 2020-01-06 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200106_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='query',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
