# Generated by Django 2.2.6 on 2020-01-06 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200106_2155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='api',
            old_name='query',
            new_name='name',
        ),
    ]
