# Generated by Django 2.2.6 on 2020-01-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200106_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='name',
            field=models.CharField(max_length=16),
        ),
    ]
