# Generated by Django 2.2.6 on 2020-01-07 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_api_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='api',
            old_name='name',
            new_name='summoner_name',
        ),
        migrations.AddField(
            model_name='api',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='api',
            name='tier',
            field=models.CharField(default='bronze', max_length=8),
        ),
        migrations.AddField(
            model_name='api',
            name='total_games',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='api',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='api',
            name='winrate',
            field=models.FloatField(default=0),
        ),
    ]
