# Generated by Django 2.2.6 on 2020-01-07 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200107_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='rank',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
