# Generated by Django 2.2.6 on 2020-01-07 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200107_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='discord_username_and_tag',
            field=models.CharField(max_length=37, null=True),
        ),
    ]
