# Generated by Django 2.2.6 on 2020-01-09 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20200109_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='api',
            name='added_by',
        ),
    ]
