# Generated by Django 2.2.6 on 2020-01-09 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_api_added_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='api',
            name='created',
        ),
    ]
